<?php

class ActionMvmt{
	
	const DRH_AVENANT = 'DRH_AVENANT';
	const DRH_ENTREE_PROLONGATION = 'DRH_ENTREE_PROLONGATION';
	const DRH_MAIL = 'DRH_MAIL';
	const DRH_SORTIE = 'DRH_SORTIE';
	const DRH_SORTIE_PROLONGATION = 'DRH_SORTIE_PROLONGATION';
	const DRI_AVENANT = 'DRI_AVENANT';
	const DRI_ENTREE = 'DRI_ENTREE';
	const DRI_ENTREE_PROLONGATION = 'DRI_ENTREE_PROLONGATION';
	const DRI_MAIL = 'DRI_MAIL';
	const DRI_SORTIE = 'DRI_SORTIE';
	const DRI_SORTIE_PROLONGATION = 'DRI_SORTIE_PROLONGATION';
	const DSI_AVENANT = 'DSI_AVENANT';
	const DSI_ENTREE = 'DSI_ENTREE';
	const DSI_ENTREE_PROLONGATION = 'DSI_ENTREE_PROLONGATION';
	const DSI_MAIL = 'DSI_MAIL';
	const DSI_SORTIE = 'DSI_SORTIE';
	const DSI_SORTIE_PROLONGATION = 'DSI_SORTIE_PROLONGATION';
	const PAP_ENTREE = 'PAP_ENTREE';
	const PAP_ENTREE_PROLONGATION = 'PAP_ENTREE_PROLONGATION';
	const PAP_ENTREE_REMPLACEMENT = 'PAP_ENTREE_REMPLACEMENT';
	const PAP_MAIL = 'PAP_MAIL';
	const PAP_SORTIE = 'PAP_SORTIE';
	const PAP_VALID_RECRUTEMENT = 'PAP_VALID_RECRUTEMENT';
	const PAP_MAJ_SORTIE = 'PAP_MAJ_SORTIE';
	const PAP_SORTIE_PROLONGATION = 'PAP_SORTIE_PROLONGATION';
}

?>